class Questions:
    QUESTIONS = [
        "Kaç yaşındasın?",
        "Hangi şehirde yaşıyorsun? Şehrin senin için ne ifade ediyor?",
        "Hangi türde bir okulda okuyorsun? (Anadolu Lisesi, Fen Lisesi, Meslek Lisesi vb.)",
        "Okul başarı seviyen nedir? (Ortalama başarı, yüksek başarı vb.)",
        "En sevdiğin ders hangisidir? Neden bu dersi seviyorsun?",
        "Gelecekte nerede yaşamak istiyorsun? Büyük bir şehir mi, yoksa daha küçük ve sakin bir yer mi?",
        "Günlük hayatında ne gibi sorumluluklar üstleniyorsun?",
        "Şu anki eğitim hayatının seni tatmin ettiğini düşünüyor musun? Hangi alanlarda gelişmek isterdin?",
        "Zamanını en çok neye harcıyorsun? (Okul, hobiler, aile, arkadaşlar vb.)",
        "Kendini 10 yıl sonra nasıl bir hayat yaşarken hayal ediyorsun?",
        "Matematik problemlerini çözmekten hoşlanır mısın? Zorlandığın oluyor mu?",
        "Teknolojik cihazlar ya da yazılımlarla aranda nasıl bir ilişki var? Yeni şeyler öğrenmekten keyif alır mısın?",
        "El becerilerini kullanarak bir şeyler inşa etmek ya da onarmaktan hoşlanır mısın?",
        "Yaratıcı fikirler üretmek ve hayal gücünü kullanmak seni ne kadar motive eder?",
        "İnsanlarla iletişim kurarken kendini rahat mı hissedersin yoksa daha içe dönük müsün?",
        "Detaylara dikkat eder misin, yoksa genel resme odaklanmayı mı tercih edersin?",
        "Problemleri çözmek için analitik düşünmeyi mi yoksa sezgisel düşünmeyi mi tercih edersin?",
        "Baskı altında çalışmak seni motive eder mi yoksa stres yaratır mı?",
        "Hangi becerilerini geliştirmek isterdin? (Örneğin, daha iyi liderlik, daha iyi teknik beceriler vb.)",
        "Zor bir projede başarısız olduğunda nasıl bir tepki verirsin?",
        "Spor yapmaktan hoşlanır mısın? Hangi sporları yapıyorsun?",
        "Müzik dinlemek, çalmak ya da şarkı söylemek seni rahatlatır mı? Ne tür müziklerle ilgilenirsin?",
        "Sanatla ilgileniyor musun? Resim, heykel veya tasarımla uğraşmak sana nasıl hissettiriyor?",
        "Teknolojiye ilgi duyuyor musun? Yeni teknolojileri keşfetmekten hoşlanır mısın?",
        "Kitap okumaktan hoşlanır mısın? Hangi tür kitaplar ilgini çeker?",
        "Boş zamanlarında ne yapmayı seversin? (Dışarı çıkmak, video oyunları oynamak, arkadaşlarla vakit geçirmek vb.)",
        "Fikirlerini başkalarıyla paylaşmaktan keyif alır mısın? Bir konuda liderlik yapmaktan hoşlanır mısın?",
        "Doğa yürüyüşleri ya da kamp gibi açık hava etkinlikleri seni ne kadar mutlu eder?",
        "Film ve dizi izlemeyi sever misin? Hangi türleri izlemeyi tercih ediyorsun?",
        "Fotoğraf çekmek, videolar oluşturmak gibi yaratıcı işlerle uğraşıyor musun?",
        "Bilim kurgu ya da felsefi tartışmalara ilgi duyar mısın?",
        "Biyoloji, kimya gibi doğa bilimlerine ilgin var mı? Hangi konuları keşfetmek isterdin?",
        "Tarih ve sosyal bilimlerle ilgili araştırmalar yapmaktan keyif alır mısın?",
        "Yabancı diller öğrenmeye açık mısın? Hangi dilleri öğrenmek isterdin?",
        "Mühendislik, mimari veya tasarım projeleri yapmayı hayal eder misin?",
        "Sosyal medya platformlarını ne sıklıkla kullanırsın? İçerik üretmeyi sever misin?",
        "Çevre, iklim değişikliği ya da sürdürülebilirlik gibi sosyal sorumluluk konularına ilgin var mı?",
        "İnsanların hayatını kolaylaştıracak teknoloji ürünleri tasarlamak ya da geliştirmek ilgini çeker mi?",
        "Hukuk ve adalet sistemine ilgin var mı? Hukuki konularda derinlemesine bilgi edinmek ister misin?",
        "Bilimsel araştırmalar yapmak ve yeni keşifler bulmak senin için heyecan verici mi?",
        "Ailen seni en çok hangi konularda destekliyor? Onların desteği senin için ne kadar önemli?",
        "Arkadaşlarınla vakit geçirdiğinde ne gibi aktiviteler yapıyorsunuz?",
        "Ailenin meslek tercihleri senin kararlarını nasıl etkiliyor? Örnek aldığın birileri var mı?",
        "Çevrende meslek sahibi olarak örnek aldığın biri var mı? Neden onu örnek alıyorsun?",
        "Ailende veya arkadaş çevrende başarılı bulduğun biri var mı? Onun hangi özelliklerini beğeniyorsun?",
        "Gönüllü olarak toplum hizmetinde bulundun mu? Bu sana nasıl bir deneyim kazandırdı?",
        "Arkadaşların ya da öğretmenlerin senin hangi yeteneklerini fark eder?",
        "Sosyal çevren seni hangi alanlarda motive ediyor?",
        "Ailenden ya da çevrenden meslek seçiminde ne tür tavsiyeler alıyorsun?",
        "Gelecekte kariyerinde aile ve sosyal çevrenin etkisinin nasıl olacağını düşünüyorsun?",
        "Hangi meslek dalında çalışmak istediğini düşündün mü? Neden o alan?",
        "Kendini daha çok bireysel çalışan biri olarak mı yoksa bir ekip üyesi olarak mı hayal ediyorsun?",
        "Çalışırken sürekli insanlarla mı yoksa daha çok bireysel işlerle mi ilgilenmek istersin?",
        "Büyük bir şehirde mi yoksa sakin bir kasabada mı çalışmak istersin? Neden?",
        "Esnek çalışma saatlerine sahip olmak mı yoksa düzenli bir programın olması mı seni daha çok motive eder?",
        "Yurt dışında çalışmak veya eğitim almak senin için cazip mi?",
        "Bir meslekte seni en çok ne motive ederdi? (Maaş, iş ortamı, topluma katkı, kişisel gelişim vb.)",
        "Gelecekte liderlik pozisyonunda mı yoksa uzmanlık pozisyonunda mı olmak istersin?",
        "Hangi meslek alanlarında daha fazla topluma fayda sağlanması gerektiğini düşünüyorsun?",
        "Çalıştığın işin sosyal ve çevresel sorumluluklarını önemsiyor musun? Neden?"
    ]

    @classmethod
    def get_question(cls, index: int) -> str:
        return cls.QUESTIONS[index]

    @classmethod
    def total_questions(cls) -> int:
        return len(cls.QUESTIONS)